version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parking-management-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - parking-network

  mysql:
    image: mysql:8.0
    container_name: parking-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - parking-network

  redis:
    image: redis:7.4
    container_name: parking-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - parking-network

networks:
  parking-network:
    driver: bridge
