version: "3.8"

services:
  app:
    build: .
    container_name: parking-management-app
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - parking-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: parking-management-mysql
    environment:
      - MYSQL_DATABASE=parking_management
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
      - ./src/main/resources/db/init/01-schema.sql:/tmp/01-schema.sql
      - ./src/main/resources/db/init/02-data.sql:/tmp/02-data.sql
    networks:
      - parking-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ppassword",
        ]
      interval: 10s
      timeout: 10s
      retries: 10

  redis:
    image: redis:7.0-alpine
    container_name: parking-management-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - parking-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  parking-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
